-   name: António José Preto
    position: CNC
    url: https://www.researchgate.net/profile/Antonio_Gomes40
    avatar: 
    
-   name: José Guilherme Almeida
    position: CNC
    url: https://www.researchgate.net/profile/Jose_Guilherme_Almeida
    avatar:

-   name: Rita Melo
    position: C2TN
    url: https://www.researchgate.net/profile/Rita_Melo
    avatar:

-   name: Carlos Barreto 
    position: CNC
    url: 
    avatar:
